narative/gatsby-theme-novela

- gatsby/node/onCreateNode.js
> let user override slug with slug field in frontmatter

- gatsby/node/onCreateWebpackConfig.js
your code refers to @types but it seems you renamed the folder at some point in time
> there is no /typings folder

- @narative/gatsby-theme-novela/gatsby-config.js
- @narative/gatsby-theme-novela/package.json
> Add gatsby-remark-external-links to gatsby-config.js

- README.md
The link was returning a 404 from Github. I've corrected it.
> fix(broken link in README.md)

- @narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
Add Medium social icon support.
> Medium icon support

- @narative/gatsby-theme-novela/README.md
- @narative/gatsby-theme-novela/gatsby-config.js
- @narative/gatsby-theme-novela/gatsby/data/data.query.js
- @narative/gatsby-theme-novela/gatsby/node/createPages.js
- @narative/gatsby-theme-novela/gatsby/node/onCreateNode.js
- @narative/gatsby-theme-novela/package.json
- @narative/gatsby-theme-novela/src/components/Code/Code.Prism.tsx
- @narative/gatsby-theme-novela/src/components/Layout/Layout.tsx
- @narative/gatsby-theme-novela/src/components/Subscription/Subscription.tsx
- @narative/gatsby-theme-novela/src/gatsby-plugin-theme-ui/colors.ts
- @narative/gatsby-theme-novela/src/gatsby-plugin-theme-ui/index.ts
- @narative/gatsby-theme-novela/src/styles/global.ts
- @narative/gatsby-theme-novela/src/templates/article.template.tsx
- README.md
- www/content/posts/2019-04-30-why-we-built-a-company-before-a-product/index.mdx
- www/gatsby-config.js
- www/package.json
- yarn.lock
Continuation of https://github.com/narative/gatsby-theme-novela/pull/70
Ready for testing/QA
> [Feature] Newsletter Subscription

- @narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
- @narative/gatsby-theme-novela/src/icons/social/Unsplash.Icon.tsx
As an Unsplash contributor, I'd like to put a link to my Unsplash profile in my author profile. 
Just added the official SVG (modified to follow the model from the other icons) + an option in SocialLinks.tsx.
IDK how many options you want to provide in the end, but I feel Unsplash should be one :)
> Adding Unsplash as an option for social

- @narative/gatsby-theme-novela/package.json
- @narative/gatsby-theme-novela/src/components/Code/Code.Prism.tsx
- www/content/posts/2019-04-31-understanding-the-gatsby-lifecycle/index.mdx
- yarn.lock
Add React-Live. This is the optional feature which is false by default so this will not bother the user who doesn't need this tools.
For user who need this (eg. for education purpose) they can enable it with add "live" after the language title.
> [Feature] <Code.Prism /> add react-live option

- .gitignore
- .prettierignore
- .travis.yml
- @narative/gatsby-theme-novela/package.json
- @narative/gatsby-theme-novela/src/types/store.d.ts
- package.json
This PR closes #52.
Contains the following subjects
To enforce code consistency
> Please note that the linting errors should be fixed outside this PR.
To make sure dependencies stay up-to-date:
Adding pre-commit hooks will greatly improve development speed and the quality of contributions. When a user does a `git commit` Husky will first run `yarn lint` locally and will not allow the commit unless linting passes.
> until eslint errors are fixed use `--no-verify` to bypass husky
Excluded from this PR because the intended solution (release-it) does not support yarn workspaces so an alternative needs to be investigated, possibly lerna.
> Continuous Integration (Linting)

- @narative/gatsby-theme-novela/gatsby-config.js
- @narative/gatsby-theme-novela/package.json
- @narative/gatsby-theme-novela/src/components/Layout/Layout.tsx
- @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
- @narative/gatsby-theme-novela/src/gatsby-plugin-theme-ui/index.ts
- www/src/html.tsx
- yarn.lock
We were using theme-ui incorrectly for Gatsby. We were using _both_ theme-ui for a regular site and the gatsby-plugin. I've changed it to only use the plugin.
Now we run into an issue where the first load still flashes white mode before going to dark on prefers dark mode.
Created an issue in theme-ui to try to get help resolving this issue.
https://github.com/system-ui/theme-ui/issues/341
> [Bug] Fixing Dark Mode on load

- @narative/gatsby-theme-novela/gatsby-config.js
- Generate feed (RSS file) depending on source of content
https://github.com/narative/gatsby-theme-novela/issues/123
> Generate feed depending of source of content

- .commitlintrc.yml
- .github/CODEOWNERS
- .travis.yml
- lerna.json
- package.json
- yarn.lock
I've been tinkering to fix #109 and #89 based on the previous great work of @bravo-kernel 
I've added commitlint to ensure commits follow conventionalcommits as this will be used for CD. 
I've added Lerna to automate the publishing. This is currently configured to generate a version and then publish it on NPM and GitHub. 
I've never really used Travis before, therefore I'm a bit clueless when it comes to how to configure it to do the automated release. 
I found this https://github.com/lerna/lerna/issues/2022 but would love to have some validation 😅
> feat: Commitlint and Lerna for CD

- @narative/gatsby-theme-novela/src/templates/author.template.tsx
Adds author name as title and author bio and description to SEO component.
Fixes #139
> feat(seo): Add meta-data to author template

- .prettierrc
> feat: add prettier config

- @narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
- @narative/gatsby-theme-novela/src/icons/index.ts
- @narative/gatsby-theme-novela/src/icons/social/Stackoverflow.Icon.tsx
- www/content/authors/authors.yml
- www/gatsby-config.js
> feat: add stackoverflow icon

- @narative/gatsby-theme-novela/src/gatsby/node/createSchemaCustomization.js
> fix: add basePath to PluginOptions type

- @narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
- @narative/gatsby-theme-novela/src/icons/index.ts
- @narative/gatsby-theme-novela/src/icons/social/DigitalOcean.Icon.tsx
- www/gatsby-config.js
> Adds DigitalOcean icon.

- @narative/gatsby-theme-novela/gatsby-config.js
> fix: merge allArticle and allContentfulPost queries

- @narative/gatsby-theme-novela/src/components/Lists/List.Ordered.tsx
- @narative/gatsby-theme-novela/src/components/Lists/List.Unordered.tsx
> fix: nest nested Lists

- @narative/gatsby-theme-novela/src/components/Figcaption/Figcaption.tsx
- @narative/gatsby-theme-novela/src/components/Figcaption/index.ts
- @narative/gatsby-theme-novela/src/components/MDX/MDX.tsx
- www/content/posts/2019-04-31-understanding-the-gatsby-lifecycle/index.mdx
Add Caption to images. Styled according to what medium does in their posts. Issue: https://github.com/narative/gatsby-theme-novela/issues/96
Here are some screenshots:
> @feature/image caption

- @narative/gatsby-theme-novela/src/styles/global.ts
Hey the iframes in the post body were awkwardly aligned. This PR is a quick fix for that.
> Fixed iframe alignment

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question_support.md
I improved the issue templates to add some prereq and auto labeling. 
Also added a template for general questions.
> feat: improve issue templates

- @narative/gatsby-theme-novela/package.json
- @narative/gatsby-theme-novela/src/components/Image/Image.Zoom.tsx
* Upgrade [react-medium-image-zoom](https://github.com/rpearce/react-medium-image-zoom#controlled-component-controlled), v3 to v4.
* Retain existing functionality.
> update react-medium-image-zoom, v3 to v4

- README.md
* Improvement: _improves documentation of the custom Logo component_ 
I start using the theme sometime ago and even though the documentation is well written I had a little bit of an issue understanding how I can change the color of my logo depending on the theme I am on ( dark/white ). 
I am adding opening this PR to improve slightly the README file where the custom logo is being described. 
Waiting for your feedback :)
> fix(docs):  regarding the custom Logo component

- @narative/gatsby-theme-novela/src/styles/global.ts
page width exceed in mobile
before:
after:
> :lipstick:(article) break word

- @narative/gatsby-theme-novela/src/gatsby/node/createPages.js
I found out in the previous change that fixed the hardcoded links: https://github.com/narative/gatsby-theme-novela/pull/300. That I'm still not able to shadow the file because it's exported instead of imported: https://www.gatsbyjs.org/docs/theme-api/. The Gatsby docs states the following about shadowing: 
`
Shadowing only works on imported files in the src directory. This is because shadowing is built on top of Webpack, so the module graph needs to include the shadowable file.
`
So here's my next PR with a request to include a permalink in the context of createPages. That way I can use the permalink to filter a Query in GraphQL which depend on the actual article …
> Adding permalink to createPage context.

- @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
- @narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx
- yarn.lock
https://github.com/narative/gatsby-theme-novela/pull/258#issuecomment-612127183
Before:
After:
No canonical url defined:
> Fix empty canonical link

- @narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
- @narative/gatsby-theme-novela/src/icons/index.ts
- @narative/gatsby-theme-novela/src/icons/social/Buymeacoffee.Icon.tsx
Adding Buymeacoffee icon support for `socialLinks`.
Here's how it looks like:
> feat(blog): add Buymeacoffee icon

- www/content/posts/2019-04-27-how-figma-changed-how-we-design/index.mdx
Fixed a typo, change wtih to with.
> fix: correct a typo

- @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
- @narative/gatsby-theme-novela/src/gatsby/node/createPages.js
- @narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx
I took the time to update the JSON-LD schema and tried to make it dynamic. I took the same approach as yoast: https://yoast.com/json-ld/ to implement the schema data.
I've also added a siteschema, this wasn't there before and I fixed a couple of og properties.
This is what the end result looks like:
```
{
"@context": "https://schema.org",
"@graph": [
{
"@type": "Organization",
"@id": "https://dannys.space/#organization",
"name": "Danny's space",
"url": "https://dannys.space",
"sameAs": [
"https://twitter.com/dannysteenman",
"https://github.com/dsteenman",
"https://www.linkedin.com/in/dannysteenman",
"https://medium.com/@dannysteenman"
],
"logo": {
"@type": "ImageObject",
"@id": "https://dannys.space/#logo",
"inLanguage": "en-US",
"url": "https://dannys.space/icons/icon-512x512.png", …
```
> Big improvement on JSON-LD for SEO

- @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
- @narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx
I've fixed the image url function for local images. And I've made an addition to the schema person description by grabbing the author bio.
> Fix image url and added schema person description

- @narative/gatsby-theme-novela/package.json
- @narative/gatsby-theme-novela/src/components/MDX/MDX.tsx
- www/content/posts/2019-04-31-understanding-the-gatsby-lifecycle/index.mdx
- yarn.lock
Addition of Social Blocks, such as Twitter, Youtube, and Github Gist. Taken from the official documentation of MDX --> https://mdxjs.com/blog/shortcodes
``` markdown
Here’s a Twitter shortcode:
<div class="Image__Small">
<Tweet tweetId="1116723357410447360" />
</div>
Here’s a YouTube shortcode:
<div class="Image__Small">
<YouTube videoId="4fHw4GeW3EU" />
<figcaption>With Small Video</figcaption>
</div>
<div class="Image__Medium">
<YouTube videoId="4fHw4GeW3EU" />
<figcaption>Caption Medium video</figcaption>
</div>
<div class="Image__Large">
<YouTube videoId="4fHw4GeW3EU" />
<figcaption>Caption Full Width video</figcaption>
</div>
Here’s a Github Gist shortcode:
<div class="Image__Medium">
<Gist id="c1d9def425feb0d51455ff7e61110a2f" />
<figcaption>Gist video</figcaption>
</div>
```
And …
> feat: mdx media blocks

- @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
- @narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx
- @narative/gatsby-theme-novela/src/types/index.d.ts
* [o] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [o] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
* [o] I have checked for an open issue related to this. _There isn't one / There is one : #XXX_
* [o] I have performed a self-review of my own code.
* [o] I have performed the necessary tests locally.
* [o] I have linted my code locally prior to submission.
* [o] If applicable, I have commented my code, particularly in hard-to-understand areas
* [o] Bug fix (_non-breaking change which fixes an issue_)
@narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
add isSecret props …
> fix: #363 add noindex meta tag to secret article

- @narative/gatsby-theme-novela/src/sections/article/Article.Next.tsx
- @narative/gatsby-theme-novela/src/sections/articles/Articles.List.tsx
This issue fixes the issue described in #383. The issue was caused by two commits:
- 82134e2190597a6a2588176e5885c2bc88ac1f0f
- 9fcb11ee7fe2bc160c01838a000ee04d76453d28
> Fix broken article links

- README.md
I only fixed small typo errors
> docs: fixed small errors

- .github/workflows/publish.yml
I had a bit of time to try and fix this once and for all (been _bugging_ me—no pun intended)
Current workflow errors at the last second with a 404:
I've looked at the Chris Biscardi example that I previously linked but it seems that recent runs of his example are getting errored as well. 
Doing some research, I found https://github.com/lerna/lerna/issues/2542 which gave some new things to try. 
TBH, not even sure this will fix it because it has been a game of whack-a-mole trying to get this to run and the issues are not obvious to understand and fix. 
Doing this as a PR to let you merge whenever you want Dennis.
> patch: workflow file

- @narative/gatsby-theme-novela/contentful/contentful-export.json
I liked this theme so I started a new project with Contentful CMS data source following the readme and ran into issues #375 , #376 and #406 .
I'm not sure what the maintainers intend to name the content field but currently using the packages below, new users cannot setup a Contentful data sourced project using the instructions on the readme.
```json
"react": "^16.13.1"
"react-dom": "16.13.1"
"gatsby": "^2.24.53"
"@narative/gatsby-theme-novela": "^0.17.0"
"gatsby-source-contentful": "^2.3.41"
```
I fixed this by using the suggestion in #376 by cloning all "Post" fields to a new content model "Article". No other fields / options were renamed / edited.
I want to contribute back so I exported the Contentful space (data models only) and tested this to be working against a new project (new npm …
> fix(contentful): update starter data model

- @narative/gatsby-theme-novela/src/sections/articles/Articles.List.tsx
> fix(Articles.List): broken margin on phablet

- @narative/gatsby-theme-novela/src/gatsby/node/createResolvers.js
- @narative/gatsby-theme-novela/src/gatsby/node/sourceNodes.js
> Added frontmatter support for articles.

- @narative/gatsby-theme-novela/src/components/Navigation/Navigation.Footer.tsx
* [x ] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [x ] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
* [x ] I have checked for an open issue related to this. _There isn't one / There is one : #454 
* [x ] If applicable, I have commented my code, particularly in hard-to-understand areas
* [x ] Bug fix (_non-breaking change which fixes an issue_)
I have implemented the solution proposed by @agillesp and validated by @yarinr but was not yet implemented. I'm experiencing the same issue.
No real context, this is a one-line fix
> fix proposed in ISSUE 454

- @narative/gatsby-theme-novela/src/gatsby/node/createResolvers.js
- @narative/gatsby-theme-novela/src/gatsby/node/sourceNodes.js
Commit 8e7a3066279f1256cfdf127e75fee518550ff173 breaks the ability to run "yarn start" and develop locally. The commit message is to add "markdown support for articles" but looks like it didn't pass the CI test and also throws an error when using "yarn start" to test local features/bug fixes with the WWW folder.
> fix: frontmatter gatsby develop bug
