narative/gatsby-theme-novela

.editorconfig, .gitignore
Hope the changes are clear. The `.vscode` files that are not ignored are files that could be used for meaningful automation.
=> Ignore .vscode and add .editorconfig

@narative/gatsby-theme-novela/gatsby/data/data.normalize.js, @narative/gatsby-theme-novela/src/sections/article/Article.Hero.tsx
solves: https://github.com/narative/gatsby-theme-novela/issues/61
When authoring, you don't want to have a hero image right away. Therefore, we should allow initial authoring to work without a defined image.
Implementation adds a warning into command line:
Site continues to run without issues. Articles list has missing hero image and Article page displays no hero.
=> [Feature] Ability to author posts without required hero

@narative/gatsby-theme-novela/src/components/Paragraph/Paragraph.tsx, @narative/gatsby-theme-novela/src/gatsby-plugin-theme-ui/index.ts
The body fonts were being set in the global styles file and weren't taking into account the sansSerif defined in theme-ui. I added this line so that fonts can be over-ridden from here. I labeled this as hotfix because I guess it was the original intention?
=> added theme-ui font sansSerif to Paragraph

@narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
Got this obscure error after upgrading, because I had a stackoverflow link to my author profile, and it took some time to figure out what was the reason
=> Make unhandled social media url more explicit

@narative/gatsby-theme-novela/gatsby/node/createPages.js
This PR applies a filter to the articles that are displayed at the bottom of the article page in more articles (next) section, preventing secret articles from showing there.
Related to Issue #63
=> More articles no longer displays secret articles

@narative/gatsby-theme-novela/gatsby/node/onCreateNode.js, README.md
This PR adds the ability to change articles URL format.
By default, it doesn't change anything (except slug format for author page but it's described below).
You can add `articlePermalinkFormat: ":year/:month/:day/:slug"` to theme options to change the article URL to `/2019/01/01/my-article`. It works also with `basePath` (`/base/2019/01/01/my-article`).
I think I've fixed one bug. Let's say that I have `basePath` set to `/blog`. Currently (in the master branch), it generates author URL as `/authors/blog/dennis-brotzky` which is not correct, is it? Now, the `basePath` is at the beginning, `/blog/authors/dennis-brotzky`.
I hope we can add this feature to the theme because it's one of the changes I need to be able to migrate my blog 😉
=> [Feature] Custom permalink for articles

@narative/gatsby-theme-novela/src/components/MDX/MDX.tsx
Quick fix to make the large image width the same as window width.
Look at the example site, https://novela.narative.co/understanding-the-gatsby-lifecycle-with-narative. The large image has a margin on the right side.
Preview: https://deploy-preview-112--gatsby-theme-novela.netlify.com/understanding-the-gatsby-lifecycle-with-narative
=> [Fix] Large image width

@narative/gatsby-theme-novela/gatsby-config.js, @narative/gatsby-theme-novela/gatsby/node/createPages.js
This PR prevents showing secret articles in the next section at the bottom of a post. See here for more details https://github.com/narative/gatsby-theme-novela/issues/63#issuecomment-526125243 Related to this PR https://github.com/narative/gatsby-theme-novela/pull/103
I've also added code to prevent showing secret articles in the RSS feed.
btw. The new lint system is great! Got it under control now.
=> Fix for secret articles in next section and RSS feed

@narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx
Fixes issue #127 
Additional fixes:
- adds `publisher` field which is required by google
- modified regex to remove whitespace inside `microdata` but not within strings enclosed with `"`. This allows the `microdata` to be stripped of white spaces while still preserving description, headline and author name white spaces.
- prepended image with `siteUrl`
- `location.href` is `undefined` when running `yarn build` causing:
```
"mainEntityOfPage":{"@type":"WebPage","@id":"undefined"}
```
To solve this I have added a static query to fetch the site name (used in `publisher`) & siteUrl which I applied to appropriate places.
You can view the [current state of structured data of Novela here](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fnovela.narative.co%2Funderstanding-t …
=> Fixes article seo structured data

@narative/gatsby-theme-novela/gatsby-config.js
=> fix: assign `sources` a default value in gatsby-config export

README.md
Please close if this is intended by design.
The tables are weird for readability when the content is center aligned. This PR left aligns them.
**Before:**
**After:**
=> docs: left align tables for readability

@narative/gatsby-theme-novela/gatsby-config.js
Not sure if it's a gatsby bug or not, but if I set `pathPrefix` on the top level, meaning when Novela is used as a plugin, then `pathPrefix` is not picked up.
=> refactor(gatsby-config): pass on pathPrefix

@narative/gatsby-theme-novela/gatsby/node/createPages.js
This PR just fixes a typo in the `createPages` hook logger.
From:
```javascript
log('Querying Authors & Aritcles source:', 'Local');
```
To:
```javascript
log('Querying Authors & Articles source:', 'Local');
```
=> chore(gatsby-node): fix typo in createPages hook

@narative/gatsby-theme-novela/gatsby-node.js, @narative/gatsby-theme-novela/gatsby/node/createPages.js, @narative/gatsby-theme-novela/gatsby/node/createSchemaCustomization.js, @narative/gatsby-theme-novela/src/components/Navigation/Navigation.Header.tsx, www/gatsby-config.js
Right now, if we click on the logo we are always taken to the `/` path. (#163)
This change adds the `rootPath` plugin option to let users define the index of their site, it then fetches the `rootPath` and uses that as the link for the logo.
=> Set rootPath to define site index

@narative/gatsby-theme-novela/src/components/MDX/MDX.tsx
This PR fixes the current issue on mobile browser view. When the content of a code-box in an article is overflowing the container, the browser apply an inflation to the content font-size automatically (tested on Safari and Chrome). This inflation make the content code font-size too big and can break the overall page typography/design since other code-boxes will retain the original size (if there is no overflow). 
Before fixe (Safari / iPhone XS) 
After fixe applied (Safari / iPhone XS) 
The fixe applied is a CSS property added to styled component PrismCSS. It prevents the browser to automatically apply the inflation algorithm to the font when there is an overflow.
=> fix: font size inflation for mobile view in code box

.github/workflows/publish.yml, .github/workflows/pulls.yml
Netlify pricing change makes no sense. Travis is a third-party. 
Moving all CI to GitHub Actions would make maintenance easier and more lean. 
pulls.yml handles the CI on PR. It basically run `yarn install && yarn lint && yarn build`. It passes if none of these commands gets an error
publish.yml is to be tested but should run `lerna publish` when master gets a new commit. 
I reused `npx` from travis.yml but since we're off travis, maybe we can just do `yarn lerna publish`
This repo should have GH Actions enabled for this to work
[] Validate that Lerna publish works with this setup. 
[] Remove travis.yml
=> feat: adding workflows for GH Actions

@narative/gatsby-theme-novela/src/components/MDX/MDX.tsx
Before:
After:
Tested in Firefox, Chrome and Brave.
=> Fixes overflow issue on code blocks.

@narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
Prevents bots from going to social link URLs. Improves website SEO/rank.
I use this on all my websites and this is the logic behind it:
When a bot crawls the page it looks for outbound links. (Outbound links are links that point the users away from your website. These types of links are most commonly found in social links.) When the bot crawls an outbound link, it follows the link and the linked page gets better rank because of that (authority etc.). This is what I call SEO leakage (I may be wrong). eg. By having an outbound link to facebook or twitter without nofollow, your website is improving the rank of Facebook or Twitter etc..
I have also read somewhere that the bots reduce your page rank because they had to index more other websites.
This PR adds `nofollow` to social links. It is …
=> SEO optimization for social links

README.md
The new `rootPath` theme option is missing in readme instructions.
This PR adds the `rootPath` definition in the theme options table and in the code example.
=> docs: add root path definition

@narative/gatsby-theme-novela/src/components/Navigation/Navigation.Footer.tsx
Closes #192 
This generates the copyright dates from the earliest and latest dates in MDX frontmatter.
I couldn't figure out how to add an optional field in `siteMetadata`, but I would still like to add an optional `footer` field to replace the copyright line if the user sets it.
=> feat: Generate copyright from content dates

@narative/gatsby-theme-novela/src/sections/article/Article.Hero.tsx, @narative/gatsby-theme-novela/src/sections/articles/Articles.List.tsx
An article's hero image can be undefined sometimes.
Somehow everything works normally when compiled on your machine, but the same code can fail when deploying. For me the issue was deploying on Zeit.
These tweaks fix the problem. I wasn't able to investigate/find a particular root cause, but it seems the theme is designed to work with missing hero images. Fixing the `hasHeroImage` flag to take undefineds into account therefore makes sense as a fix.
=> Fix references to missing hero image

@narative/gatsby-theme-novela/src/components/Navigation/Navigation.Footer.tsx
The query inside the `Navigation.Footer` was getting all the `MDX` files inside the project which also includes the authors' description. 
I simply add a `filter` in order to exclude the other `.mdx` without date, which will take out the documents we don't want to check.
=> fix(Navigation.Footer): wrong year

README.md
Improve document because it's missing author's social url & can not start the project. Explained at #228
=> [docs] Improve Getting Started document

@narative/gatsby-theme-novela/src/components/Headings/Headings.tsx
We can improve readability of Korean page by just add style `word-break: keep-all`.
- without `keep-all`
- with `keep-all`
=> <feat>: Add style `word-break: keep-all` to Headings

www/gatsby-config.js
There were 2 stackoverflow links in the footer. I am unsure why there were 2 links so I am making a pull request with one of them deleted.
They seem to have come in at the commits:
* [A way to manually set the icon for social link #187](https://github.com/narative/gatsby-theme-novela/pull/187)
* [feat: add stackoverflow icon #171](https://github.com/narative/gatsby-theme-novela/pull/171)
The link is also mentioned in Issue #156: [Social Stackoverflow / custom value](https://github.com/narative/gatsby-theme-novela/issues/156) 
I kept the link with the name and url because it was the only link using that syntax in gatsby-config.js
=> fix: (www/gatsby-config.js) Remove duplicate stackoverflow link in footer

www/gatsby-config.js
Closes #249 
Shouldn't be using a remote data source in CI for the example app imo. Still fails but fails with the error listed here: https://github.com/gatsbyjs/gatsby/issues/15397
=> fix: Fix build by changing source to local for www

@narative/gatsby-theme-novela/package.json, @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx, @narative/gatsby-theme-novela/src/gatsby/data/data.query.js, @narative/gatsby-theme-novela/src/gatsby/node/createPages.js, @narative/gatsby-theme-novela/src/gatsby/node/onCreateNode.js, @narative/gatsby-theme-novela/src/gatsby/node/sourceNodes.js, @narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx, CONTRIBUTING.md, www/content/posts/2019-04-31-understanding-the-gatsby-lifecycle/index.mdx, yarn.lock
Canonical Tags are needed when duplicate page content exists across the web. Search Engines use these tags to make sure only the content without the tag will be prioritized. Personally, I use these as I cross-post my content across multiple websites.
reference: https://moz.com/learn/seo/canonicalization
This package already uses [React Helmet](https://github.com/nfl/react-helmet) so adding the canonical tag can be done easily. Check out the example in the [README](https://github.com/nfl/react-helmet#example) of that package.
These tags must be specified on a per-article basis so a new frontmatter property was created named `canonical_url`. To have this prop be used in the article template, I needed to add it to [how Gatsby creates …
=> Add canonical_url support to articles

@narative/gatsby-theme-novela/src/gatsby/node/createPages.js
Fixes https://github.com/narative/gatsby-theme-novela-example/issues/7
Add back the defaults to sources to maintain original behaviour. Currently both local and contentful are not set by default, causing the default gatsby-config.js to fail.
=> Fix: Add back defaults to sources

.github/pull_request_template.md
Realized we hadn't a PR template so I made one. 
Might create some overhead but I feel it'd help document the PR for the repo and guide new contributors.
Feel free to close it if it's not useful :)
=> docs: add a PR template

@narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
The SEO component renders twitter meta tags in the header. It uses the social data, but doesn't fetch the `name` property which is needed later on to retrieve the twitter specific part.
In this PR, I'm adding the right field to fetch, fixing the `creator` twitter tag.
Before:
After:
=> fix: fetch social name for twitter meta tags

@narative/gatsby-theme-novela/gatsby-browser.js, @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
Currently the fonts are loaded via Google Fonts, which are increasing the length of the critical request chains. That can be observed in the PageInsightTool from Google.
In this PR, I'm suggesting to load the fonts locally using the typeface module, already part of the bundle. This way, the RT is way faster and help the speed of the first page load. All the fonts are there, including bold and italic.
BEFORE:
AFTER:
NOTE: I'm not entirely sure why the package is part of the bundle and the fonts are still required via `<link>` tag so I might miss something here. Feel free to close it if that doesn't make sense :)
=> fix: load fonts locally

@narative/gatsby-theme-novela/gatsby-node.js
I had the following issue when adding a new component which requires to pass a context variable: https://github.com/narative/gatsby-theme-novela/issues/292
I was unable to shadow the createPages.js file in the src/gatsby/node folder. I found out that the gatsby-node.js contains hardcoded links for the node exports. This PR should address it so I'm able to shadow the node components in my own repository.
=> Fix: Hardcoded exports from node_modules

@narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
This is a fix for issue: https://github.com/narative/gatsby-theme-novela/issues/308. When you are using Contentful, the metadata image was populated using your own domain + the image location. Since the images are hosted on https://images.ctfassets.net it returned a faulty url.
=> Checks if the source of the image is hosted on Contentful

@narative/gatsby-theme-novela/gatsby-config.js
The previous RSS feed was broken for Contentful posts. The url's were missing "/" which meant the links and guids didn't work. I've also enabled the body of the post, so you can have a proper RSS feed and possible integration using medium or dev.to.
=> Fix Contentful RSS feed url's

@narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx
I noticed that the article SEO image url was broken because of the Contentful post. This PR fixes it.
Output of "image" before this fix:
```
{"@context":"https://schema.org","@type":"Article","mainEntityOfPage":{"@type":"WebPage","@id":"https://dannys.space/ready-up-for-the-aws-advanced-networking-exam"},"headline":"Ready up for the AWS Advanced Networking exam","image":"https://dannys.space//images.ctfassets.net/6issw7wxujml/1W1TRZpXoLP9mVR2YLxVh0/51a9f9f2e57f10d165897eccf9cbbf3f/advancednetworkhero.jpg?w=1200&q=100","datePublished":"2020-02-01T13:00+01:00","dateModified":"2020-02-01T13:00+01:00","author":[{"@type":"Person","name":"Danny Steenman"}],"description":"Prepare to read a lot of study material 📚","publisher":{"@type":"Organization","name":"Danny …
```
=> Fixed article SEO img for contentful image source.

.github/workflows/publish.yml, @narative/gatsby-theme-novela/gatsby-node.js, www/package.json
We do not want to generate a new lockfile when running yarn install in github actions. This can cause unwanted deps to be installed in CI. We want it to use the lockfile generated by the developers.
https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-pure-lockfile
=> Fix yarn install command in GitHub action script

@narative/gatsby-theme-novela/src/sections/article/Article.Share.tsx
This addresses issue #319, fixing a broken CSS element in the article share menu. Simple case of changing the value of the right margin.
=> Fix: broken CSS in article share menu

@narative/gatsby-theme-novela/src/components/SEO/SEO.tsx
I saw that contentful updated the image link and added "https:" themselves. So it's not required anymore.
=> Removed hardcoded "https:" for SEO

@narative/gatsby-theme-novela/src/components/SEO/SEO.tsx, @narative/gatsby-theme-novela/src/sections/article/Article.SEO.tsx
The content of the meta og:url was empty (seems like the helmet prop "url" is empty):
```
<meta property="og:url" content="" data-react-helmet="true">
```
With this fix:
```
<meta property="og:url" content="https://dannys.space/ready-up-for-the-aws-advanced-networking-exam" data-react-helmet="true">
```
og:site_name used the wrong property, this is fixed as well. I've added og:type to the mix as well.
=> Fix og:url and added og:type and og:site_name

@narative/gatsby-theme-novela/contentful/contentful-export.json, @narative/gatsby-theme-novela/src/components/SEO/SEO.tsx, @narative/gatsby-theme-novela/src/gatsby/node/onCreateNode.js
A couple of issues reported that the slug of articles etc.. contained uppercase randomly. I updated the generateSlug function to fix this issue. And while I was at it a bug popped it with the meta image (og|twitter) that wouldn't show the preview.jpg because of the order of the statement. So that's fixed as well.
=> Fix: generateSlug function to create lowercase and default preview image

@narative/gatsby-theme-novela/src/components/Navigation/Navigation.Header.tsx
Found a bug when playing around with this today: On mobile, navigate to page 2 by pressing "Next". Now navigate back to page 1 by pressing "Prev". The navigating header will be the back arrow. Clicking it will take you back to page 2, which makes no sense.
=> fix: stop showing back button on home page

@narative/gatsby-theme-novela/src/gatsby/node/onCreateNode.js
Fixed the default mixed-case slug which causes “Page with redirect” issues in Google search console. Redirects are typically not advisable for SEO (as they can affect search engine indexing issues and adversely affect site loading time). (As per #309)
While keeping the power of `slug` key which overrides the autogenerated `lower case` slug based on the blog title/author's name. (Broken in #326 as per #336)
=> fix(blog): default mixed-case slug

@narative/gatsby-theme-novela/src/components/SocialLinks/SocialLinks.tsx
Changed the regex in `replace()` of `getHostname()` of `SocialLinks.tsx` to handle notion.so's url.
=> fix: notion icon error due to replace regex not handling .so domain.

@narative/gatsby-theme-novela/gatsby-config.js, @narative/gatsby-theme-novela/src/gatsby/node/onCreateNode.js
Raw JS with MDX content is appearing in RSS.xml for local articles. In the original PR, it was decided not to support article content because the author's (and this one) don't know how to process the body. That line was mistakenly uncommented later.
I've added a comment to clarify the reason for the line being commented out.
=> fix: remove unprocessed JS content from local articles in RSS

@narative/gatsby-theme-novela/src/gatsby/data/data.query.js
* [ x] I have followed the guidelines in our [Contributing Guidelines](https://github.com/narative/gatsby-theme-novela/blob/master/CONTRIBUTING.md). _Especially our commitlint_
* [ x] I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/fix/change.
Fixes error in GraphQL query: 'Cannot query field "allContentfulPost" on type "Query".' when using Contentful datasource and the Starter. 
Appears to be due to mixing Article & Post terminology. Attempted to resolve within the [contentful-export.json](https://github.com/narative/gatsby-theme-novela/tree/master/%40narative/gatsby-theme-novela/contentful) without success. Renaming query resolved.
=> fix for starter and contentful import

@narative/gatsby-theme-novela/gatsby-config.js
PR#365 renamed this contentful post query from allContentfulPost --> allContentfulArticle. Renaming more references to it in gatsby-config.js. 
Resolves this issue introduced by PR#365:
Error: Cannot query field "allContentfulPost" on type "Query". Did you mean "a llContentfulAsset", "contentfulAsset", "allContentfulAuthor", "allContentfulAr ticle", or "allContentfulContentType"? GraphQL request:3:17 2 | { 3 | allContentfulPost(sort: {order: DESC, fields: date}) { | ^ 4 | edges { - internals.js:15
=> rename allContentfulPost --> allContentfulArticle

@narative/gatsby-theme-novela/gatsby-config.js, @narative/gatsby-theme-novela/src/sections/article/Article.Next.tsx, @narative/gatsby-theme-novela/src/sections/articles/Articles.List.tsx
Next article links are relative to current page and throw 404. Concatenated forward slash to article slug to root them.
`<ArticleLink
to={"/"+article.slug}
data-a11y="false"
narrow={narrow ? "true" : "false"}
>`
=> relative article next links 404, make rooted

@narative/gatsby-theme-novela/src/sections/author/Author.Hero.tsx
Fixed a bug where the bio of the author is displayed as text on Author's page. Please see the #372 issue description.
=> fix: Render bio as HTML on Author's page

@narative/gatsby-theme-novela/src/templates/article.footer.template.tsx, @narative/gatsby-theme-novela/src/templates/article.template.tsx
This PR pulls out the Mailchimp subscription box into its own component, allowing us to easily use the existing component shadowing to attach footers to every post without modifying the entire article template.
=> feat: Added ability to implement a custom article footer

@narative/gatsby-theme-novela/src/styles/global.ts
Hey there, I published my first article using this theme and I have detected that this theme is not using the `line-break` CSS property; if we are not using it, all long words, text, or URL links can break the layout.
Maybe my comments above are not so clear, but screen captures can help.
This is my blog article where you can replicate the issue:
https://josejesus.dev/Crea-tu-propio-grid-system
At the end of my article, I added two links:
You can resize the browser window in small resolutions to confirm how long words/text can break the article layout.
It could be solved easily with the `line-break: anywhere` rule in the `:root` element.
=> fix: Long words, text, or URL links could break the article layout (small resolutions)

@narative/gatsby-theme-novela/contentful/contentful-export.json
Contentful throws errors when using non-required fields for content models. Setting `required` to `true` when importing the content models into Contentful resolves all errors.
Errors are listed below:
```
ERROR #85923  GRAPHQL
There was an error in your GraphQL query:
Cannot query field "secret" on type "ContentfulArticle".
If you don't expect "secret" to exist on the type "ContentfulArticle" it is most likely a typo.
However, if you expect "secret" to exist there are a couple of solutions to common problems:
- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields …
```
=> Make all Contentful fields required

@narative/gatsby-theme-novela/src/components/Tables/Table.Cell.tsx
When using a Markdown table which contains wide Images, the text tags are being pushed and start to break apart, making them almost unreadable ...
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3399429/97231486-cd070c80-17db-11eb-899c-3d35479a3307.png) | ![image](https://user-images.githubusercontent.com/3399429/97231460-c4aed180-17db-11eb-82cd-8236aee467fa.png) |
=> fix: word-break inside TableCell

@narative/gatsby-theme-novela/src/styles/global.ts
Hi there, this pull request addresses an issue introduced by pull request #431. The merge added a global `line-break` change which allowed line breaks to be introduced anywhere. 
I believe the intention was to allow URLs to adjust their line breaks as dimensions changed, but because it was applied globally, it negatively impacts other areas such as the hero text, author bio, and date within the article. See below as an example:
This is what the above image looks like with the removal of the erroneous `line-break` change:
=> Fix breaking line-break change

@narative/gatsby-theme-novela/gatsby-config.js
Formerly, the emotion gatsby plugin was using an unrecognized option name. It should be `autoLabel` instead of `displayName`.
=> fix: update gatsby-plugin-emotion option
